### ISSUE TITLE
Feature request: support for "in progress" status

### ISSUE THREAD

**Issue by boyoungzheng** [heliostatic/completed-task-display#19]
Do not hide "in progres " status (- [/]) as introduced by the [Tasks plugin](https://publish.obsidian.md/tasks/Getting+Started/Statuses/Custom+Statuses).

**Comment by jankoweb** [comment]
You can update plugin's css:
```
body.hide-completed-tasks .markdown-preview-view ul > li.task-list-item.is-checked,
body.hide-completed-tasks .markdown-source-view .HyperMD-task-line[data-task="x"] {
  display: none;
}
```

**Comment by dassagichnicht** [comment]
Here is the adapted css to only hide tasks with status x (completed)
```css
body.hide-completed-tasks .markdown-preview-view ul > li.task-list-item.is-checked[data-task='x'],
body.hide-completed-tasks .markdown-source-view .HyperMD-task-line[data-task='x']:not([data-task=" "]) {
    display: none;
    }
}"])
```
