### ISSUE TITLE
Live preview support

### ISSUE THREAD

**Issue by jamie9090** [heliostatic/completed-task-display#5]
Love this - but possible for it to work on live preview?

**Comment by 23maverick23** [comment]
@jamie9090 

If you want to patch this yourself, you can edit `.obsidian/plugins/completed-task-display/styles.css` with the following CSS which _should_ work.

```css
body.hide-completed-tasks .markdown-preview-view ul > li.task-list-item.is-checked,
body.hide-completed-tasks .markdown-source-view .HyperMD-task-line[data-task]:not([data-task=" "]) {
  display: none;
}
```
